#Database
H2_USERNAME: ADMIN
H2_PASSWORD: 12345
H2_PATH: jdbc:h2:mem:db
POSTGRES_PATH: jdbc:postgresql://localhost/GroupManager
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: 09082001

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: frontend.shchetinin@gmail.com
EMAIL_PASSWORD: ykaxvjihaqcdxpxc
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

#JWT
JWT_SECRET: 9DAA6FB2F0F0E8324EA5C5CEAE1525321D0B3C5450633D85F3074BD43B763785